spring.application.name=SoundCloud

# spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.hibernate.ddl-auto=update
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3307/soundcloud?createDatabaseIfNotExist=true
# spring.datasource.url=jdbc:mysql://localhost:3306/soundcloud
spring.datasource.username=root
spring.datasource.password=1607
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=false
# color terminal
spring.output.ansi.enabled=ALWAYS
#start page = 1
spring.data.web.pageable.one-indexed-parameters=true

# use git bash here
#config jwt
# openssl rand -base64 64
djnd.jwt.base64-secret=nE6Od1T/x2GDldpDXhd9uaXfQupvYU7fCgO4IXPG3B2on76ZvM9hmGT7CR4sOPZmVu8R7u4+Uwy9Zik+fOwq9A==
djnd.jwt.access-token-validity-in-seconds=604800
djnd.jwt.refresh-token-validity-in-seconds=1296000

## config email with Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=voanhbendjnd@gmail.com
spring.mail.password=qrywyweqefmjrqqc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
###

#config upload file
###
#default = 1MB
spring.servlet.multipart.max-file-size=100MB

#default = 10 MB (form data)
spring.servlet.multipart.max-request-size=100MB

djnd.upload-file.base-uri=C:/Users/PC/Documents/Backend/Project/upload/soundcloud/


# import file other properties
spring.config.import=optional:classpath:roles.properties, optional:classpath:storage.properties


# Config Redis Cache
spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.redis.time-to-live=3600000

# YouTube Data API v3
youtube.api.key=${YOUTUBE_KEY}
spring.data.redis.timeout=700

# config server 8GB
spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.lettuce.pool.max-idle=8
spring.data.redis.lettuce.pool.min-idle=2
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.batch_versioned_data=true




djnd.soundcloud.cloudinary.name=${CLOUD_NAME}
djnd.soundcloud.cloudinary.key=${API_KEY_CLOUD}
djnd.soundcloud.cloudinary.secret=${API_SECRET_CLOUD}

# audiowaveform configuration
djnd.soundcloud.audiowaveform.path=C:/Users/PC/Documents/Backend/audiowaveform.exe
