djnd.soundcloud.location.folder.audio=audio-tracks
djnd.soundcloud.location.folder.img=img-tracks
djnd.soundcloud.location.folder.temp=temp-tracks
djnd.soundcloud.location.folder.avatar=avatar
djnd.soundcloud.location.folder.waveform=waveforms