services:
  mysql-db: # <--- Đây là tên SERVICE
    image: mysql:8.0
    container_name: mysql-local
    restart: always
    environment:
      MYSQL_DATABASE: soundcloud
      MYSQL_ROOT_PASSWORD: 1607
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  redis-music: # <--- Đây là tên SERVICE
    image: redis:alpine
    container_name: redis-local
    restart: always
    ports:
      - "6379:6379"

  # backend-app:
  #   build: .
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./temp_processing:/app/uploads
  #   environment:
  #     # TRONG DOCKER: Dùng tên service và cổng nội bộ 3306
  #     - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/soundcloud
  #     - UPLOAD_DIR=/app/uploads
  #   depends_on:
  #     - mysql-db    # <--- Phải khớp với tên ở trên
  #     - redis-music # <--- Phải khớp với tên ở trên